package com.swiggy;

import lombok.Data;
import java.security.SecureRandom;

/**
 * This Class Represents a Dice,that can be rolled to generate random outcomes.
 */

@Data //Getters and setters are automatically generated by Lombok's @Data annotation
public class Dice {

    private int sides;
    private SecureRandom randomNumber;

    /**
     * Rolls the dice and return the random number generated
     *
     * @return random integer between 1 and sides
     */

    public int roll() {
        return randomNumber.nextInt(sides) + 1;
    }


}

